language: go

os:
  - osx
  - windows
  - linux

go:
  - 1.15.x
  - 1.16.x

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go";
    export PATH="$GOPATH/bin:$PATH"; fi
  - mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"

install:
  - go get -u golang.org/x/lint/golint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
  - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

script:
  - go get -v ./...
  - |-
    case $TRAVIS_OS_NAME in
      linux|osx)
        golint ./... | reviewdog -f=golint -reporter=github-check
        golangci-lint run --out-format=line-number -E goimports -E misspell | reviewdog -f=golangci-lint -reporter=github-check
        golint ./... | reviewdog -f=golint -reporter=github-pr-review
        golangci-lint run --out-format=line-number -E goimports -E misspell | reviewdog -f=golangci-lint -reporter=github-pr-review
        ;;
    esac
  - go test -v -benchmem -test.bench=".*" -coverprofile=coverage.txt -covermode=atomic  ./...

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -s https://codecov.io/bash >
    .codecov && chmod +x .codecov && ./.codecov; else bash <(curl -s https://codecov.io/bash);
    fi

env:
  global:
    - GO111MODULE=on
    - secure: h6hh6xoOVMqV9zgoyKqcxGohNH2+DslZDDenVOimOhVdG076Jzwl+nmpxmpd3epB86cPIxZWamxkKpqYq4zwvAt53ObiIatBs3LUTRuE7Zp9KsfGfsD5Xoq5mehzaM0f9azGbpOjdBMpz563MprylbSgnsivhs89pFXx11gMF/SQ2ak1rIFuhQQxW8TqxXzZgnfJx9Kjtq2luA/psz/B5ftgL3FTWRE/8Covga6bFG/hiEkcTc6qJz5hPkoD0q1kc2klLJszhgA4Bte6NvinFDrB25BrhUB58Od1UVzy5cmJ1WE+20BDc9FvTcikeKjA430cXkIk4j1XaSGzIO5qyoiRMEXUVyr2RYZ0xNtu+1esMmGttpUep9kPXNYgFD950ccO31iSqQeK/yjWw9Ts8jrUZWoP1v59mJ+DFkqQOg0hAkglGs4kwXJfw9W4tXy1OZw+UutxWifpHEJ9as8GPcaOJJSaJFrz8Jz1VICEV5uNf7LhA+wJJoIIyCplz9IHnjnFucGwmKKnxJNL28YuQg3BnpDA/Extmxc61NTACqoIXT/LU2gTipDlHtA1HCBeJJpe5XGwZqiT7eNUv3KHWA77JrzsCiyQti+ARqqMkCqZmp+SnfQ3XIKowkilecMHFEc2YltbIZv17dxjrRiPnh7aAh5b3mAYZyJd1BuEHd0=